Treat empty blocks with MinItems == 0 as optional
hashicorp/terraform-plugin-docs pull request #99
Opened 2021-12-02 21:02 UTC by ovandriyanov

This patch allows for generating documentation for those providers which have empty objects in their schema, i.e, the objects no attributes and no nested blocks.

Terraform allows providers to have empty objects in their schema, but the currently terraform-plugin-docs cannot generate docs for such providers and raises an error like the following:

    no match for empty_block_field, this can happen if you have incompatible schema
    defined, for example an optional block where all the child attributes are
    computed, in which case the block itself should also be marked computed

Fix it by handling such empty blocks explicitly.

2021-12-02 21:02 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform-plugin-docs?pullRequest=99)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform-plugin-docs?pullRequest=99)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform-plugin-docs?pullRequest=99).</sub>

2022-03-16 18:36 UTC, GennadySpb commented
@bflad Please check this PR: I got same issue as #100

2022-04-26 09:01 UTC, detro approved these changes

2022-04-26 09:02 UTC, detro requested changes
Sorry, erroneous approval.

This is good, but we need `BUG FIXES` entry added to the `CHANGELOG`

2022-04-26 09:06 UTC, detro commented
Sorry, I think I should have been more explicit.

The changelog format is defined here https://www.terraform.io/plugin/sdkv2/best-practices/versioning#changelog-specification .

Your change will be part of `0.8.0`.

2022-05-03 17:04 UTC, closed without merging